# Generated by Django 5.1.6 on 2025-03-07 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('nh4', models.FloatField(verbose_name='% NH4')),
                ('nh3', models.FloatField(verbose_name='% NH3')),
                ('n', models.FloatField(verbose_name='% N')),
                ('p2o5', models.FloatField(verbose_name='% P2O5')),
                ('k2o', models.FloatField(verbose_name='% K2O')),
                ('cao', models.FloatField(verbose_name='% CaO')),
                ('mgo', models.FloatField(verbose_name='% MgO')),
                ('so3', models.FloatField(verbose_name='% SO3')),
                ('s', models.FloatField(verbose_name='% S')),
                ('fe', models.FloatField(verbose_name='% Fe')),
                ('mn', models.FloatField(verbose_name='% Mn')),
                ('b', models.FloatField(verbose_name='% B')),
                ('zn', models.FloatField(verbose_name='% Zn')),
                ('cu', models.FloatField(verbose_name='% Cu')),
                ('mo', models.FloatField(verbose_name='% Mo')),
                ('co', models.FloatField(verbose_name='% Co')),
                ('si', models.FloatField(verbose_name='% Si')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
