# Generated by Django 5.1.6 on 2025-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_fertilizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='b',
            field=models.FloatField(default=0, verbose_name='% B'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='cao',
            field=models.FloatField(default=0, verbose_name='% CaO'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='co',
            field=models.FloatField(default=0, verbose_name='% Co'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='cu',
            field=models.FloatField(default=0, verbose_name='% Cu'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='fe',
            field=models.FloatField(default=0, verbose_name='% Fe'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='k2o',
            field=models.FloatField(default=0, verbose_name='% K2O'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='mgo',
            field=models.FloatField(default=0, verbose_name='% MgO'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='mn',
            field=models.FloatField(default=0, verbose_name='% Mn'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='mo',
            field=models.FloatField(default=0, verbose_name='% Mo'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='n',
            field=models.FloatField(default=0, verbose_name='% N'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='nh3',
            field=models.FloatField(default=0, verbose_name='% NH3'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='nh4',
            field=models.FloatField(default=0, verbose_name='% NH4'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='p2o5',
            field=models.FloatField(default=0, verbose_name='% P2O5'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='s',
            field=models.FloatField(default=0, verbose_name='% S'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='si',
            field=models.FloatField(default=0, verbose_name='% Si'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='so3',
            field=models.FloatField(default=0, verbose_name='% SO3'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='zn',
            field=models.FloatField(default=0, verbose_name='% Zn'),
        ),
    ]
