# Generated by Django 5.1.6 on 2025-03-08 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_fertilizer_n'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='so3',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='cl',
            field=models.FloatField(default=0, verbose_name='% Cl'),
        ),
        migrations.CreateModel(
            name='P_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('nh4', models.FloatField(default=0, verbose_name='мг/л NH4')),
                ('nh3', models.FloatField(default=0, verbose_name='мг/л NH3')),
                ('p', models.FloatField(default=0, verbose_name='мг/л P')),
                ('k', models.FloatField(default=0, verbose_name='мг/л K')),
                ('ca', models.FloatField(default=0, verbose_name='мг/л Ca')),
                ('mg', models.FloatField(default=0, verbose_name='мг/л Mg')),
                ('s', models.FloatField(default=0, verbose_name='мг/л S')),
                ('cl', models.FloatField(default=0, verbose_name='мг/л Cl')),
                ('fe', models.FloatField(default=0, verbose_name='мкг/л Fe')),
                ('mn', models.FloatField(default=0, verbose_name='мкг/л Mn')),
                ('b', models.FloatField(default=0, verbose_name='мкг/л B')),
                ('zn', models.FloatField(default=0, verbose_name='мкг/л Zn')),
                ('cu', models.FloatField(default=0, verbose_name='мкг/л Cu')),
                ('mo', models.FloatField(default=0, verbose_name='мкг/л Mo')),
                ('co', models.FloatField(default=0, verbose_name='мкг/л Co')),
                ('si', models.FloatField(default=0, verbose_name='мкг/л Si')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
