# Generated by Django 5.1.6 on 2025-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_fertilizer_so3_fertilizer_cl_p_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_profile',
            name='b',
            field=models.FloatField(default=0, verbose_name='B, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='ca',
            field=models.FloatField(default=0, verbose_name='Сa, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='cl',
            field=models.FloatField(default=0, verbose_name='Cl, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='co',
            field=models.FloatField(default=0, verbose_name='Co, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='cu',
            field=models.FloatField(default=0, verbose_name='Cu, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='fe',
            field=models.FloatField(default=0, verbose_name='Fe, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='k',
            field=models.FloatField(default=0, verbose_name='K, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='mg',
            field=models.FloatField(default=0, verbose_name='Mg, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='mn',
            field=models.FloatField(default=0, verbose_name='Mn, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='mo',
            field=models.FloatField(default=0, verbose_name='Mo, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='nh3',
            field=models.FloatField(default=0, verbose_name='NH3, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='nh4',
            field=models.FloatField(default=0, verbose_name='NH4, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='p',
            field=models.FloatField(default=0, verbose_name='P, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='s',
            field=models.FloatField(default=0, verbose_name='S, мг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='si',
            field=models.FloatField(default=0, verbose_name='Si, мкг/л'),
        ),
        migrations.AlterField(
            model_name='p_profile',
            name='zn',
            field=models.FloatField(default=0, verbose_name='Zn, мкг/л'),
        ),
    ]
