# Generated by Django 5.1.6 on 2025-03-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_p_profile_b_alter_p_profile_ca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='nh3',
        ),
        migrations.RemoveField(
            model_name='p_profile',
            name='nh3',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='no3',
            field=models.FloatField(default=0, verbose_name='% NO3'),
        ),
        migrations.AddField(
            model_name='p_profile',
            name='no3',
            field=models.FloatField(default=0, verbose_name='NO3, мг/л'),
        ),
    ]
