# Generated by Django 5.1.6 on 2025-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_fertilizer_nh3_remove_p_profile_nh3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_profile',
            name='growth_stage',
            field=models.CharField(choices=[('start', 'Старт'), ('veg', 'Вегетация'), ('late_veg', 'Поздняя вегетация'), ('fruiting', 'Плодоношение')], default='start', max_length=20, verbose_name='Стадия роста'),
        ),
    ]
